"""
    BrainlessLab

An extensible Julia tinkering lab for brainless reservoirs, bodies, tasks, and
ensembles. The high-level workflow is intentionally two lines:

    sim = simulate(:tracking; node=:falandays)
    visualize(sim)

Load CairoMakie or another Makie backend before plotting; the compute core stays
Makie-free.
"""
module BrainlessLab

import Base: summary, view

include("core/Interfaces.jl")
include("core/Traits.jl")
include("core/Params.jl")
include("core/Specifications.jl")
include("evolution/Evolution.jl")
include("evolution/Artifacts.jl")
include("core/Registry.jl")
include("core/Components.jl")
include("core/Recorder.jl")
include("core/Parallel.jl")
include("viz/Style.jl")
include("viz/Views.jl")
include("nodes/Drives.jl")
include("nodes/Axes.jl")
include("world/Torus.jl")
include("world/Arena.jl")
include("world/Ports.jl")
include("world/Sensor.jl")
include("world/Response.jl")
include("world/SpatialFields.jl")
include("world/SpectralVision.jl")
include("world/BilateralSensing.jl")
include("world/Body.jl")
include("world/Motor.jl")
include("world/PhysicalComponents.jl")
include("world/Interaction.jl")
include("world/Embodiment.jl")
include("world/SectorVision.jl")
include("world/Homeostasis.jl")
include("nodes/SpikeHistory.jl")
include("nodes/Falandays.jl")
include("nodes/SORN.jl")
include("nodes/Compartmental.jl")
include("nodes/Wiring.jl")
include("nodes/CompartmentalReservoir.jl")
include("nodes/Interventions.jl")
include("nodes/NullRandom.jl")
include("nodes/HomeostaticFlowSupport.jl")
include("nodes/HomeostaticFlowV2.jl")
include("envs/WallBox.jl")
include("envs/Envs.jl")
include("envs/CartPoleVariants.jl")
include("envs/PlankCartPole.jl")
include("tasks/Scoring.jl")
include("tasks/Tasks.jl")
include("core/Composition.jl")
include("world/Environments.jl")
include("world/Ensemble.jl")
include("world/Metrics.jl")
include("api/paper_config.jl")
include("api/Highlevel.jl")
include("core/Catalog.jl")
include("api/Composition.jl")
include("operations/Plans.jl")
include("operations/Evaluation.jl")
include("operations/Profile.jl")
include("operations/Sweep.jl")
include("operations/Ablation.jl")
include("operations/Evolution.jl")
include("operations/Benchmark.jl")
include("records/PlanIO.jl")
include("records/ExperimentIO.jl")
include("records/Records.jl")
include("records/Contributions.jl")
include("analysis/ActivityLevels.jl")
include("analysis/Branching.jl")
include("analysis/Avalanches.jl")
include("analysis/TargetError.jl")
include("analysis/Spectral.jl")
include("analysis/SecondOrder.jl")
include("analysis/SwarmAnalysis.jl")
include("analysis/NullTest.jl")
include("analysis/TaskSignals.jl")
include("analysis/TransferEntropy.jl")
include("analysis/ForageTransfer.jl")
include("analysis/OwnColour.jl")
include("tasks/Calibration.jl")
include("run/EmbodimentConfig.jl")
include("run/ComponentCatalog.jl")
include("world/ObjectWorld.jl")
include("tasks/ShoalForage.jl")
include("analysis/ShoalForage.jl")
include("run/Development.jl")
include("run/Replay.jl")
include("api/PublicAPI.jl")

register_drive!(:none, NoDrive)
register_drive!(:oosawa, OosawaDrive)

register_node!(
    :falandays,
    _falandays_native;
    genome_type=FalandaysParams,
    receptor_profile_keyword=:input_link_p,
)
register_node!(:sorn, _sorn_native; genome_type=SORNParams)
register_node!(:compartmental_dense, _compartmental_dense_native; genome_type=DenseCompartmental)
register_node!(:compartmental_structured, _compartmental_structured_native; genome_type=StructuredCompartmental)
register_node!(:null_random, NullRandomReservoir)
register_node!(:homeostatic_flow_v2, HomeostaticFlowV2Reservoir; genome_type=HomeostaticFlowV2Params)

register_task!(:wall, WALL_TASK)
register_task!(:tracking, TRACKING_TASK)
register_task!(:pong, PONG_TASK)
register_task!(:pong_hitrate, PONG_HITRATE_TASK)
register_task!(:cartpole, CARTPOLE_TASK)
register_task!(:cartpole_hard, CARTPOLE_HARD_TASK)
register_task!(:cartpole_swingup, CARTPOLE_SWINGUP_TASK)
register_task!(:cartpole_long, CARTPOLE_LONG_TASK)
register_task!(:cartpole_plank_easy, CARTPOLE_PLANK_EASY_TASK)
register_task!(:cartpole_plank_medium, CARTPOLE_PLANK_MEDIUM_TASK)
register_task!(:cartpole_plank_hard, CARTPOLE_PLANK_HARD_TASK)
register_task!(:cartpole_plank_hardest, CARTPOLE_PLANK_HARDEST_TASK)
register_task!(:torus, TORUS_TASK)
register_task!(:forage, FORAGE_TASK)
register_task!(:shoal_forage, SHOAL_FORAGE_TASK)

register_body!(:direct, Embodiment)

register_motor!(:situated_kinematics, KinematicMotor)

register_sensor!(:bearing_cone, BearingSensor)

register_metric!(:polarization, polarization)
register_metric!(:milling, milling)
register_metric!(:mean_pairwise_distance, mean_pairwise_distance)
register_metric!(:mean_nearest_neighbor_distance, mean_nearest_neighbor_distance)
register_metric!(:segregation, segregation)
register_metric!(:input_stability, input_stability)
register_metric!(:swarm_metrics, swarm_metrics)
register_metric!(:forage_metrics, forage_metrics)

register_analysis!(:branching_ratio, branching_ratio; label="branching ratio (experimental)")
register_analysis!(:branching_ratio_mr, branching_ratio_mr; label="branching ratio m (MR estimator, subsampling-robust) (experimental)")
register_analysis!(:branching_ratio_mr_windowed, branching_ratio_mr_windowed; label="windowed branching ratio m (MR estimator) (experimental)")
register_analysis!(:branching_ratio_mr_conditioned, branching_ratio_mr_conditioned; label="branching ratio m split by object-in-view vs drift (experimental)")
register_analysis!(:avalanches, avalanches; label="thresholded avalanche sizes, durations, and intervals (experimental)")
register_analysis!(:node_transfer_entropy, node_transfer_entropy; label="node-level transfer entropy (experimental)")
register_analysis!(:agent_transfer_entropy, agent_transfer_entropy; label="agent-level transfer entropy (experimental)")
register_analysis!(:node_target_error, node_target_error; label="per-node distance to target |act−T|")
register_analysis!(:spectral_radius, spectral_radius; label="spectral radius ρ(W)")
register_analysis!(:susceptibility, susceptibility; label="susceptibility χ (experimental)")
register_analysis!(:susceptibility_windowed, susceptibility_windowed; label="windowed susceptibility χ (experimental)")
register_analysis!(:fano_factor, fano_factor; label="activity-rate summary (mean, variance, Fano)")
register_analysis!(:participation_ratio, participation_ratio; label="participation ratio (experimental)")
register_analysis!(:swarm_regime, swarm_regime; label="swarm regime classifier (experimental)")
register_analysis!(:correlation_length, correlation_length; label="swarm velocity correlation length (experimental)")
register_analysis!(:correlation_length_windowed, correlation_length_windowed; label="windowed swarm velocity correlation length (experimental)")
register_analysis!(:contact_graph_clusters, contact_graph_clusters; label="contact-graph connected-component clusters (experimental)")
register_analysis!(:contact_graph_clusters_windowed, contact_graph_clusters_windowed; label="windowed contact-graph connected-component clusters (experimental)")
register_analysis!(:crossshift_null, crossshift_null; label="per-agent circular-shift null test (experimental)")
register_analysis!(:temporal_null, temporal_null; label="within-network condition-shuffle null test")
register_analysis!(:distance_to_source, distance_to_source; task=:forage, label="mean distance to forage source")
register_analysis!(:forage_alignment, forage_alignment; task=:forage, label="follower source-alignment (Vanni C, experimental)")
register_analysis!(:lookout_follower_te, lookout_follower_te; task=:forage, label="lookout→follower transfer entropy (experimental)")
register_analysis!(:own_colour_decodability, own_colour_decodability; task=:torus, label="own-colour decodability from reservoir state (experimental)")
register_analysis!(:wall_distance, wall_distance; task=:wall, label="distance to nearest wall")
register_analysis!(:heading_error, heading_error; task=:tracking, label="heading error (rad)")
register_analysis!(:object_in_view, object_in_view; task=:tracking, label="stimulus-in-view indicator (experimental)")
register_analysis!(:ball_paddle_distance, ball_paddle_distance; task=:pong, label="ball–paddle distance")
register_analysis!(:shoal_need_satisfaction, shoal_need_satisfaction; task=:shoal_forage, label="material and association need satisfaction (exploratory)")
register_analysis!(:shoal_contact_summary, shoal_contact_summary; task=:shoal_forage, label="resource contact and alternation summary (exploratory)")
register_analysis!(:shoal_movement_summary, shoal_movement_summary; task=:shoal_forage, label="recorded movement diagnostics (exploratory)")
register_analysis!(:shoal_group_movement_summary, shoal_group_movement_summary; task=:shoal_forage, label="proximity cohesion and movement coherence (exploratory)")
register_analysis!(:shoal_perceptual_graph, shoal_perceptual_graph; task=:shoal_forage, label="dynamic conspecific perceptual graph (exploratory)")

register_view!(:raster, rasterplot)
register_view!(:rate, rateplot)
register_view!(:trajectory, trajectoryplot)
register_view!(:swarm, swarmplot)
register_view!(:network, networkplot)
register_view!(:drift, driftplot)
register_view!(:fitness, fitnessplot)
register_view!(:visualize, visualize)
register_view!(:explore, explore)
register_view!(:replay, replay)
register_view!(:animate, animate)

register_ablation!(:reset_dendrites, ResetDendrites)
register_ablation!(:no_soma_back, NoSomaBack)
register_ablation!(:no_hillock_back, NoHillockBack)
register_ablation!(:freeze_plasticity, FreezePlasticity)
register_ablation!(:zero_recurrent, ZeroRecurrent)
register_ablation!(:clamp_target, ClampTarget)
register_ablation!(:disable_vision, DisableVision)

register_builtins!(DEFAULT_REGISTRY)

end
