"""Static host boundary for the released Quadrants 1.3.3 DSL.

Kernel expressions are dynamically compiled, so scalar expression values are
Any. Array ownership, host transfers, shape access, callable arguments and
frozen bundle fields remain checked. These stubs never affect live annotations.
"""

from collections.abc import Callable, Iterable
from typing import Any, overload

import numpy as np

from . import lang as lang
from . import math as math
from . import types as types

i32 = int
i64 = int
f32 = float
f64 = float

cpu: Any
metal: Any
__version__: tuple[int, int, int]

class ndarray:
    shape: tuple[int, ...]
    dtype: Any
    def __init__(self, dtype: Any, shape: tuple[int, ...] | int) -> None: ...
    def __class_getitem__(cls, arguments: Any) -> type[ndarray]: ...
    def from_numpy(self, value: np.ndarray) -> None: ...
    def to_numpy(self) -> np.ndarray: ...
    def fill(self, value: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

@overload
def kernel[F: Callable[..., Any]](function: F, *, fastcache: bool = ..., **options: Any) -> F: ...
@overload
def kernel[F: Callable[..., Any]](
    function: None = ..., *, fastcache: bool = ..., **options: Any
) -> Callable[[F], F]: ...
def func[F: Callable[..., Any]](function: F) -> F: ...
def template(*args: Any, **kwargs: Any) -> Any: ...
def init(**options: Any) -> None: ...
def sync() -> None: ...
def reset() -> None: ...
def static(value: Any) -> Any: ...
def cast(value: Any, dtype: Any) -> Any: ...
def ndrange(*ranges: int | tuple[int, int]) -> Iterable[Any]: ...
def abs(value: Any) -> Any: ...
def min(*values: Any) -> Any: ...
def max(*values: Any) -> Any: ...
def sin(value: Any) -> Any: ...
def cos(value: Any) -> Any: ...
def exp(value: Any) -> Any: ...
def sqrt(value: Any) -> Any: ...
def ceil(value: Any) -> Any: ...
def floor(value: Any) -> Any: ...
def atan2(y: Any, x: Any) -> Any: ...
